/**
 * Category-wise keyword data (Google Keyword Planner export, Jul 2025 - Jun 2026)
 * Volume = avg monthly searches. Sorted high to low per category.
 * Generator isko prompt me feed karta hai taaki content real search demand
 * ke hisab se bane, guess se nahi.
 */

export const CATEGORY_KEYWORDS = {
  rummy: [
    { keyword: "yono rummy", volume: 5000000 },
    { keyword: "yono rummy apk", volume: 500000 },
    { keyword: "yono rummy games", volume: 500000 },
    { keyword: "yono rummy app", volume: 50000 },
    { keyword: "yono rummy apps", volume: 50000 },
    { keyword: "yono rummy download", volume: 50000 },
    { keyword: "all yono rummy", volume: 50000 },
    { keyword: "new yono rummy", volume: 50000 },
    { keyword: "yono rummy list", volume: 5000 },
    { keyword: "yono rummy 2026", volume: 5000 },
  ],
  slots: [
    { keyword: "yono slots", volume: 500000 },
    { keyword: "yono slots apk", volume: 50000 },
    { keyword: "yono slots download", volume: 50000 },
    { keyword: "yono slot games", volume: 50000 },
    { keyword: "yono slots games", volume: 50000 },
    { keyword: "all yono slots", volume: 50000 },
    { keyword: "yono slots list", volume: 5000 },
    { keyword: "new yono slots", volume: 5000 },
    { keyword: "yono slots app", volume: 5000 },
    { keyword: "yono slots 2026", volume: 500 },
  ],
  "777": [
    { keyword: "yono 777", volume: 5000000 },
    { keyword: "yono 777 apk", volume: 50000 },
    { keyword: "yono 777 download", volume: 50000 },
    { keyword: "yono 777 games", volume: 50000 },
    { keyword: "yono 777 app", volume: 5000 },
    { keyword: "yono 777 apps", volume: 5000 },
    { keyword: "yono 777 slots", volume: 5000 },
    { keyword: "all yono 777", volume: 5000 },
    { keyword: "new yono 777", volume: 5000 },
    { keyword: "yono 777 2026", volume: 5000 },
    { keyword: "yono 777 list", volume: 500 },
  ],
  vip: [
    { keyword: "yono vip", volume: 500000 },
    { keyword: "yono vip apk", volume: 50000 },
    { keyword: "yono vip games", volume: 50000 },
    { keyword: "yono vip app", volume: 5000 },
    { keyword: "yono vip apps", volume: 5000 },
    { keyword: "yono vip download", volume: 5000 },
    { keyword: "all yono vip", volume: 5000 },
    { keyword: "new yono vip", volume: 500 },
    { keyword: "yono vip 2026", volume: 500 },
    { keyword: "yono vip list", volume: 50 },
  ],
  spin: [
    { keyword: "yono spin", volume: 50000 },
    { keyword: "yono spin games", volume: 50000 },
    { keyword: "all yono spin", volume: 5000 },
    { keyword: "yono spin apk", volume: 500 },
    { keyword: "yono spin app", volume: 500 },
    { keyword: "yono spin apps", volume: 500 },
    { keyword: "yono spin download", volume: 500 },
    { keyword: "yono spin list", volume: 50 },
    { keyword: "new yono spin", volume: 50 },
    { keyword: "yono spin 2026", volume: 50 },
  ],
  diwa: [
    { keyword: "diwa vip", volume: 50000 },
    { keyword: "diwa 777", volume: 50000 },
    { keyword: "diwa game", volume: 5000 },
    { keyword: "diwa games", volume: 5000 },
    { keyword: "diwa slots", volume: 5000 },
    { keyword: "diwa 777 apk", volume: 500 },
    { keyword: "diwa apk", volume: 500 },
    { keyword: "diwa game apk", volume: 500 },
    { keyword: "diwa vip apk", volume: 500 },
    { keyword: "all diwa games", volume: 500 },
    { keyword: "diwa apps", volume: 50 },
    { keyword: "diwa download", volume: 50 },
    { keyword: "new diwa games", volume: 50 },
  ],
};